#!/usr/bin/env bash
if git diff --cached --name-only | grep -E 'GoogleService-Info.*\.plist' >/dev/null; then
  echo "❌ Blocking commit: GoogleService-Info*.plist should not be committed."
  exit 1
fi
if git diff --cached --name-only | grep -E '(^|/)Info\.plist$' >/dev/null; then
  echo "❌ Blocking commit: Info.plist should not be committed."
  exit 1
fi
